### PR TITLE
Add xdg directory spec option

### PR DESCRIPTION
**Pull request by epsilon-phase**
It's nice to have config stuff placed in `~/.config/msync`, if for no other reason that it tends to jive better with the typical behavior of linux/unix/mac software.

### CODE REVIEW

**Comment by Kansattica** [comment]
Hm, would the more general option be to allow the user to configure a directory for msync to look in, which could be `~/.config/msync` rather than introducing special code for xdg? I'd be willing to keep the XDG_CONFIG_HOME stuff in there regardless.

**Comment by epsilon-phase** [comment]
that would be an option yeah.

What kinda behavior do you want for default then?

**Comment by epsilon-phase** [comment]
Hmm, that should probably be changed

**Comment by Kansattica** [comment]
Hey, this is a little awkward, but there's a good chance I'm gonna go with Ben's, just because his does the XDG stuff and some other stuff besides. If you'd like to work with him on adding base directory stuff or do host-meta stuff, I'd be willing to take that.

Sorry about this, this is not a situation I ever expected to happen, honestly.

**Comment by epsilon-phase** [comment]
It's alright. We understand

**Pull request closed without merging**
