### PR TITLE
debian installer

### PR DESCRIPTION
**Pull request by BenLubar**

### CODE REVIEW

**Comment by Kansattica** [comment]
Looking good! Note that if `logs_off` is set to true, `msync` still creates an empty `msync.log` file when it starts. Check the `disablelog` branch to see what you have to do to not touch the file at at all.

**Comment by BenLubar** [comment]
rebased and fixup'd related commits

**Comment by Kansattica** [comment]
Hey, I updated the .travis.yml file on master so it actually tests if these preprocessor includes work. Can I ask you to merge up or rebase one more time?

**Comment by BenLubar** [comment]
split related changes to #26 and #27

**Pull request merged**
